version: '3.8'

services:
  web:
    build:
      context: .
    container_name: waste_management
    env_file: .env
    volumes:
      - .:/food_waste_management
    expose:
      - "8000"
    depends_on:
      - db
      - redis


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: postgres_waste_management
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_food_waste_management
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: celery_worker
    env_file: .env
    command: celery -A food_waste_management worker --loglevel=info
    volumes:
      - .:/food_waste_management
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
    container_name: celery_beat
    env_file: .env
    command: celery -A food_waste_management beat --loglevel=info
    volumes:
      - .:/food_waste_management
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
