name: Django CI/CD with Docker & Elastic Beanstalk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ---------------------------
  # 1. TEST JOB (CI)
  # ---------------------------
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker images with secrets
        run: |
          POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }} \
          AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }} \
          docker-compose build

      - name: Run migrations and tests
        run: |
          POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
          AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }} \
          AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }} \
          docker-compose run --rm web sh -c "python manage.py migrate --noinput && python manage.py test"

  # ---------------------------
  # 2. DEPLOY JOB (CD)
  # ---------------------------
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Update EB environment variables
      - name: Update EB environment variables
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --option-settings \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=AWS_STORAGE_BUCKET_NAME,Value=${{ secrets.AWS_STORAGE_BUCKET_NAME }} \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=AWS_S3_REGION_NAME,Value=${{ secrets.AWS_S3_REGION_NAME }} \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=POSTGRES_USER,Value=${{ secrets.POSTGRES_USER }} \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=POSTGRES_PASSWORD,Value=${{ secrets.POSTGRES_PASSWORD }} \
              Namespace=aws:elasticbeanstalk:application:environment,OptionName=DATABASE_NAME,Value=${{ secrets.DATABASE_NAME }}

      - name: Zip source code
        run: zip -r deploy.zip .

      - name: Install EB CLI
        run: |
          pip install --upgrade pip
          pip install awsebcli

      - name: Initialize EB application
        run: |
          eb init ${{ secrets.EB_APP_NAME }} --platform "Docker" --region ap-south-1

      - name: Select EB environment
        run: |
          eb use ${{ secrets.EB_ENV_NAME }}

      - name: Deploy to Elastic Beanstalk
        run: eb deploy
