name: Django CI/CD with Docker & Elastic Beanstalk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DATABASE_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        run: docker compose build

      - name: Run migrations and tests inside container
        run: |
          docker compose run --rm web sh -c "python manage.py migrate --noinput && python manage.py test"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # sirf main branch pe hi deploy kare

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Zip source code for deployment
        run: zip -r deploy.zip .

      - name: Install EB CLI
        run: |
          pip install awsebcli

      - name: Initialize EB application
        run: |
          eb init ${{ secrets.EB_APP_NAME }} --platform "Docker" --region ap-south-1

      - name: Select EB environment
        run: |
          eb use ${{ secrets.EB_ENV_NAME }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
